### ISSUE TITLE
Technical difficulties

### ISSUE THREAD

**Issue by desvasicek** [Abinde-Game-Dev/Abinde#6]
See my issue: https://github.com/pypa/build/issues/508#issue-1332153080

**Comment by henryiii** [comment]
FYI, `'importlib-metadata; python_version >= "3.8"',` is probably backwards, usually you want `importlib-metadata` before some version of Python - it's a backport. Newer versions have `importlib.metdata` that you can use directly.

I'd recommend adding a minimal pyproject.toml, and maybe even using it for all config and removing setup.py entirely. See https://packaging.python.org/en/latest/tutorials/packaging-projects/ & https://scikit-hep.org/developer/pep621 for that method.

**Comment by desvasicek** [comment]
Thanks!

**Comment by desvasicek** [comment]
I just realized my mistake 😲 it says `python_version is less than 3.8`. Thanks so much!
